name: Deploy to Github Pages

on: [push]

jobs:
  Deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
    - name: Deploy
      uses: dgr8akki/github-action-gh-pages@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLIC_PATH: ${{ secrets.PUBLIC_PATH }}
        PUSH_BRANCH: ${{ secrets.PUSH_BRANCH }}
        CI: true
