name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, deploy
      run: |
        git config --local user.email "pahujaaakash5@gmail.com"
        git config --local user.name "dgr8akki"
        npm install
        npm run deploy
      env:
        CI: true
