on: push
name: Build and deploy - yml Version
jobs:
  Deployment:
    name: Filter Master
    runs-on: ubuntu-latest
    on:
      push:
        branches:
          - develop
    steps:
    - name: Npm install
      run: |
        npm install
    - name: Npm build
      run: |
        npm run build
    - name: Deploy
      uses: dgr8akki/github-action-gh-pages@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLIC_PATH: ${{ secrets.PUBLIC_PATH }}
        PUSH_BRANCH: ${{ secrets.PUSH_BRANCH }}
