on: push
name: Build and deploy
jobs:
  filterMaster:
    name: Filter Master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Filter Master
      uses: actions/bin/filter@b2bea07
      with:
        args: branch master
    - name: Npm install
      uses: actions/npm@e7aaefe
      with:
        args: install
    - name: Npm build
      uses: actions/npm@e7aaefe
      with:
        args: run build
    - name: Deploy
      uses: dgr8akki/github-action-gh-pages@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLIC_PATH: ${{ secrets.PUBLIC_PATH }}
        PUSH_BRANCH: ${{ secrets.PUSH_BRANCH }}
