on:
  push:
    branches:
      - develop

name: Build and deploy - yml Version
jobs:
  Deployment:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to develop
      uses: actions/checkout@master
      with:
        ref: develop
    - name: Npm install
      run: |
        npm install
    - name: Npm build
      run: |
        npm run build
    - name: Deploy
      uses: dgr8akki/github-action-gh-pages@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLIC_PATH: ${{ secrets.PUBLIC_PATH }}
        PUSH_BRANCH: ${{ secrets.PUSH_BRANCH }}
